# Basic
title: Jane's Dev
subtitle: 
welcome_message: <a href="https://janecheng07.github.io/" target="_blank">修炼iOS，偏执追求完美</a>
description: Jane's Development Life.
creator: <a href="http://janecheng07.github.io/">@janecheng</a>

url: "http://janecheng07.github.io/"

permalink: /:year/:month/:title/

# Format
highlighter: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color:

# The blog button should not be removed.
blog_button:
    title: 博客
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: 项目, description: My Projects, url: 'http://github.com/JaneCheng07'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: janecheng
    # duoshuo: 
    
# Social
social:
    github: JaneCheng07
    mail: jane33cheng@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
